---
name: Flow Deployer
on:
  workflow_dispatch:

jobs:
  # First, run the script that exports the Connect flows against account-one
  export-flows:
    runs-on: ubuntu-latest
    environment: account-one
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: setup aws creds
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          role-to-assume: ${{ secrets.ROLE_ARN }}
          role-session-name: github-actions-deploy
          aws-region: eu-west-2
          audience: ${{ secrets.AWS_AUDIENCE }}

      - name: run some command
        run: |
          aws s3 ls

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' #install the python needed
          cache: 'pip' # caching pip dependencies
      
      - name: run python script  
        run: |
          pip install boto3
          python export_cf.py

      - name: commit changes back to repo??
        uses: stefanzweifel/git-auto-commit-action@v4

  deploy-flows:
    needs: export-flows
    runs-on: ubuntu-latest
    environment: account-two
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: setup aws creds
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          role-to-assume: ${{ secrets.ROLE_ARN }}
          role-session-name: github-actions-deploy
          aws-region: eu-west-2
          audience: ${{ secrets.AWS_AUDIENCE }}

      - name: run some command
        run: |
          aws s3 ls
